name: PR labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '20'
          m_label: 'size/m'
          m_max_size: '50'
          l_label: 'size/l'
          l_max_size: '100'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 100 lines.
            Please ensure that you are NOT addressing multiple issues in one PR.
            If the PR is atomic and focuses on a single change, it helps the maintainers.
          github_api_url: 'api.github.com'
          files_to_ignore: ''
